baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "https://www.howe-jones.co.uk/" # the base hostname & protocol for your site

exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
exclude: [vendor]

twitter_username: agile_geek
github_username:  chrishowejones
